---
ops: [train, evaluate]
model: {
    path: <ABSOLUTE_PATH>/selene/manuscript/case2/deeper_deepsea_arch.py,
    class: DeeperDeepSEA,
    class_args: {
        sequence_length: 1000,
        n_targets: 919,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_online_sampler/data/male.hg19.fasta,
        blacklist_regions: hg19
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_online_sampler/data/distinct_features.txt
    },
    target: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_online_sampler/data/sorted_deepsea_data.bed.gz,
    intervals_path: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_online_sampler/data/TF_intervals.txt,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    seed: 127,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    feature_thresholds: 0.5,
    mode: train,
    save_datasets: [train, test, validate]
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 64,
    max_steps: 960000,
    report_stats_every_n_steps: 64000,
    n_validation_samples: 16000,
    n_test_samples: 640000,
    use_cuda: True,
    data_parallel: True,
    logging_verbosity: 2
}
output_dir: <ABSOLUTE_PATH>/selene/manuscript/case2/online_sampler_outputs
random_seed: 1447
create_subdirectory: False
...
